[halftone]
name = "halftone"
description = "Retro halftone dot pattern effect"
scale = 8.0
intensity = 0.8
dot_size_min = 0.1
dot_size_max = 0.9

[wave-gradient]
name = "wave-gradient"
description = "Animated wave with color gradients"
wave_frequency = 0.02
wave_amplitude = 30.0
colors = ["#ff6b6b", "#4ecdc4", "#45b7d1", "#96ceb4", "#ffeaa7"]
blend_factor = 0.6

[disruptor]
name = "disruptor"
description = "Digital glitch disruption effect"
noise_intensity = 0.15
displacement_factor = 5.0
color_shift_red = 25
color_shift_blue = 35
frequency = 0.1

[cyberpunk]
name = "cyberpunk"
description = "Neon cyberpunk scanlines"
line_spacing = 3
line_opacity = 0.1
glow_color = "#00ff88"
flicker_intensity = 0.05

[matrix]
name = "matrix"
description = "Digital rain matrix effect"
rain_density = 0.02
rain_speed = 2.0
fade_factor = 0.95
color_primary = "#00ff00"
color_secondary = "#008800"