name = "Dracula"
author = "Zeno Rocha"
variant = "dark"

# Core colors
background = "#282a36"
foreground = "#f8f8f2"
cursor = "#f8f8f2"
selection = "#44475a"
currentLine = "#44475a"
lineNumber = "#6272a4"

# Base syntax colors
comment = "#6272a4"
string = "#f1fa8c"
number = "#bd93f9"
keyword = "#ff79c6"
operator = "#ff79c6"
function = "#50fa7b"
variable = "#f8f8f2"
constant = "#bd93f9"
type = "#8be9fd"
class = "#8be9fd"

# Extended syntax colors
property = "#8be9fd"
attribute = "#50fa7b"
tag = "#ff79c6"
regexp = "#ff5555"
punctuation = "#f8f8f2"
decorator = "#50fa7b"

# Language-specific markup
[markup]
heading = "#bd93f9"
bold = "#ffb86c"
italic = "#f1fa8c"
link = "#8be9fd"
code = "#50fa7b"
quote = "#6272a4"
list = "#ff79c6"

# Diff colors
[diff]
added = "#50fa7b"
removed = "#ff5555"
changed = "#ffb86c"

# UI elements
[ui]
error = "#ff5555"
warning = "#ffb86c"
info = "#8be9fd"
success = "#50fa7b"