name = "GitHub Dark"
author = "GitHub"
variant = "dark"

# Core colors
background = "#0d1117"
foreground = "#c9d1d9"
cursor = "#c9d1d9"
selection = "#3b5179"
currentLine = "#161b22"
lineNumber = "#8b949e"

# Base syntax colors
comment = "#8b949e"
string = "#a5d6ff"
number = "#79c0ff"
keyword = "#ff7b72"
operator = "#ff7b72"
function = "#d2a8ff"
variable = "#ffa657"
constant = "#79c0ff"
type = "#f0883e"
class = "#f0883e"

# Extended syntax colors
property = "#79c0ff"
attribute = "#7ee787"
tag = "#7ee787"
regexp = "#a5d6ff"
punctuation = "#c9d1d9"
decorator = "#d2a8ff"

# Language-specific markup
[markup]
heading = "#79c0ff"
bold = "#ffa657"
italic = "#a5d6ff"
link = "#79c0ff"
code = "#7ee787"
quote = "#8b949e"
list = "#ff7b72"

# Diff colors
[diff]
added = "#3fb950"
removed = "#f85149"
changed = "#d29922"

# UI elements
[ui]
error = "#f85149"
warning = "#d29922"
info = "#58a6ff"
success = "#3fb950"