name = "Monokai Pro"
author = "monokai.pro"
variant = "dark"

# Core colors
background = "#2d2a2e"
foreground = "#fcfcfa"
cursor = "#fcfcfa"
selection = "#5b595c"
currentLine = "#373438"
lineNumber = "#727072"

# Base syntax colors
comment = "#727072"
string = "#ffd866"
number = "#ab9df2"
keyword = "#ff6188"
operator = "#ff6188"
function = "#a9dc76"
variable = "#fcfcfa"
constant = "#ab9df2"
type = "#78dce8"
class = "#78dce8"

# Extended syntax colors
property = "#78dce8"
attribute = "#a9dc76"
tag = "#ff6188"
regexp = "#fc9867"
punctuation = "#939293"
decorator = "#ffd866"

# Language-specific markup
[markup]
heading = "#78dce8"
bold = "#fc9867"
italic = "#ab9df2"
link = "#78dce8"
code = "#a9dc76"
quote = "#727072"
list = "#ff6188"

# Diff colors
[diff]
added = "#a9dc76"
removed = "#ff6188"
changed = "#fc9867"

# UI elements
[ui]
error = "#ff6188"
warning = "#fc9867"
info = "#78dce8"
success = "#a9dc76"