name = "Tokyo Night"
author = "enkia"
variant = "dark"

# Core colors
background = "#1a1b26"
foreground = "#a9b1d6"
cursor = "#c0caf5"
selection = "#33467c"
currentLine = "#24283b"
lineNumber = "#3b4261"

# Base syntax colors
comment = "#565f89"
string = "#9ece6a"
number = "#ff9e64"
keyword = "#bb9af7"
operator = "#89ddff"
function = "#7aa2f7"
variable = "#c0caf5"
constant = "#ff9e64"
type = "#2ac3de"
class = "#ff9e64"

# Extended syntax colors
property = "#73daca"
attribute = "#7aa2f7"
tag = "#f7768e"
regexp = "#b4f9f8"
punctuation = "#a9b1d6"
decorator = "#bb9af7"

# Language-specific markup
[markup]
heading = "#7aa2f7"
bold = "#ff9e64"
italic = "#bb9af7"
link = "#2ac3de"
code = "#9ece6a"
quote = "#565f89"
list = "#f7768e"

# Diff colors
[diff]
added = "#9ece6a"
removed = "#f7768e"
changed = "#e0af68"

# UI elements
[ui]
error = "#f7768e"
warning = "#e0af68"
info = "#7aa2f7"
success = "#9ece6a"